name: relateddigital_flutter
description: Related Digital Flutter SDK
version: 0.0.3
homepage: https://github.com/relateddigital/relateddigital-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: relateddigital_flutter.relateddigital_flutter
        pluginClass: RelateddigitalFlutterPlugin
      ios:
        pluginClass: RelateddigitalFlutterPlugin