package com.relateddigital.flutter

object Constants {
    var CHANNEL_NAME = "relateddigital_flutter"
    var M_PERMISSION = "RD/requestPermission"
    var M_INIT = "RD/init"
    var M_TOKEN_RETRIEVED = "RD/getToken"
    var M_NOTIFICATION_OPENED = "RD/openNotification"
    var M_EURO_USER_ID = "RD/setEuroUserId"
    var M_EMAIL_WITH_PERMISSION = "RD/setEmailWithPermission"
    var M_SET_EMAIL = "RD/setEmail"
    var M_USER_PROPERTY = "RD/setUserProperty"
    var M_REMOVE_USER_PROPERTY = "RD/removeUserProperty"
    var M_APP_VERSION = "RD/setAppVersion"
    var M_NOTIFICATION_PERMISSION = "RD/setPushNotificationPermission"
    var M_EMAIL_PERMISSION = "RD/setEmailPermission"
    var M_PHONE_PERMISSION = "RD/setPhoneNumberPermission"
    var M_BADGE = "RD/setBadgeCount"
    var M_ADVERTISING = "RD/setAdvertisingIdentifier"
    var M_TWITTER = "RD/setTwitterId"
    var M_FACEBOOK = "RD/setFacebookId"
    var M_CUSTOM_EVENT = "VL/customEvent"
    var M_REGISTER_EMAIL = "RD/registerEmail"
    var M_RECOMMENDATIONS = "VL/getRecommendations"
    var M_STORY_ITEM_CLICK = "VL/onStoryItemClick"
    var M_STORY_CLEAR_CACHE = "VL/clearStoryCache"
    var M_FAV_ATTRIBUTE = "VL/getFavAttributes"
    var M_LOGOUT = "VL/logout"
    var M_LOGIN = "VL/login"
    var M_SIGNUP = "VL/signUp"
    var M_GET_EXVISITORID = "VL/getExVisitorID"
    var M_APP_TRACKER = "VL/appTracker"
    var M_GET_PUSH_MESSAGES = "RD/getPushMessages"
    var M_SEND_LOCATION_PERMISSION = "VL/sendLocationPermission"
    var VL_CHANNEL = "Android"
    var VL_SEGMENT_URL = "https://lgr.visilabs.net"
    var VL_REALTIME_URL = "https://rt.visilabs.net"
    var VL_TARGET_URL = "https://s.visilabs.net/json"
    var VL_ACTION_URL = "https://s.visilabs.net/actjson"
    var VL_GEOFENCE_URL = "https://s.visilabs.net/geojson"
    var VL_REQUEST_TIMEOUT = 30
    var STORY_VIEW_NAME = "StoryView"
    var REGISTER_TOKEN = "RegisterToken"
}